# Use the official Node.js image
FROM node:16

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install --force

# Copy the rest of your application code
COPY . .

# Expose the port your app runs on
EXPOSE 4000


# Start the application
CMD ["npm", "run", "start"]
